app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('aboutMe/', views.aboutMe, name='aboutMe'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contactMe, name='contactMe'),
    path('schedule/', views.mySchedule, name='mySchedule'),
    path('appointments/', views.appointments, name='appointments'),
    path('delete/<int:ids>', views.delete, name='delete')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
import datetime

# Create your models here.
class Schedule(models.Model):
    appointment = models.CharField(max_length=50)
    date = models.DateField(default=datetime.date.today)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def getAll():
        allObjects = Schedule._meta.model.objects.all()
        result = [i for i in allObjects]
        return result

    def getDate(self):
         return str(self.date)
    
    def getStartTime(self):
        return self.start_time

    def getEndTime(self):
        return self.end_time
    
    def getAppointmentName(self):
        return str(self.appointment)
    
    def getTime(self):
        return str(self.start_time) + " - " + str(self.end_time)

        

app/forms.py
from django import forms
from .models import Schedule

class NewAppointment(forms.Form):
    appointment = forms.CharField(label="Appointment", max_length=50)
    date = forms.DateField()
    start_time = forms.TimeField()
    end_time = forms.TimeField()

app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import NewAppointment
from .models import Schedule
import datetime
import calendar

# Create your views here.
def index(request):
    return render(request, 'index.html')

def aboutMe(request):
    return render(request, 'aboutMe.html')


def gallery(request):
    return render(request, 'gallery.html')

def contactMe(request):
    return render(request, 'contactMe.html')

def mySchedule(request):
    scheduleObject = Schedule.getAll()
    schedule = [i.getDate().day for i in scheduleObject]
    cal = calendar.monthcalendar(datetime.date.today().year, datetime.date.today().month)
    calList = [i for i in k for k in cal]
    appointment = []
    for i in calList:
        for j in schedule:
            if i == j:
                appointment.append(j)
    firstday = [i.pop(0) for i in cal]
    w1 = cal[0]
    w2 = cal[1]
    w3 = cal[2]
    w4 = cal[3]
    w5 = cal[4]

    if request.method == "POST":
        form = NewAppointment(request.POST)
        if form.is_valid():
            cleanAppointment = form.cleaned_data["appointment"]
            cleanDate = form.cleaned_data["date"]
            cleanTime = form.cleaned_data["time"]
            t = Schedule(appointment=cleanAppointment, date=cleanDate, time=cleanTime)
            t.save()

            return HttpResponse("<h1>Good Job</h1>")
    elif request.method == "GET":
        form = NewAppointment()
        return render(request, 'mySchedule.html', {"form":form, "cal":cal, "w1":w1, "w2":w2, "w3":w3, "w4":w4, "w5":w5, "firstday":firstday, "appointment": appointment})

def appointments(request):
    appointments = Schedule.objects.all()
    if request.method == "POST":
        form = NewAppointment(request.POST)

        if form.is_valid():
            cleanAppointment = form.cleaned_data["appointment"]
            cleanDate = form.cleaned_data["date"]
            cleanStartTime = form.cleaned_data["start_time"]
            cleanEndTime = form.cleaned_data["end_time"]
            t = Schedule(appointment=cleanAppointment, date=cleanDate, start_time=cleanStartTime, end_time=cleanEndTime)
            t.save()
            return redirect('/appointments/')
    elif request.method == "GET":
        form = NewAppointment()
        return render(request, 'appointments.html', {"form":form, "appointments":appointments})

def delete(request, ids):
    item = Schedule.objects.get(id = ids)
    item.delete()
    form = NewAppointment()
    updatedAppointments = Schedule.objects.all()
    return redirect('/appointments/')

app/templates/aboutMe.html
{% extends 'base.html' %}
    {% block title %}About Me{% endblock %}
      {% block content %}
        <div class="jumbotron">
          <h1>Welcome to my gallery</h1>
            <div class="row">
                <div class="col-md">
                  <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Walk from the Past</h5>
                    </div>
                  </div>
                </div>
                <div class="col-md">
                  <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Walk in the Park</h5>
                    </div>
                  </div>
                </div>
                <div class="col-md">
                  <div class="card" style="width: 18rem;">
                    <img src="..." class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">Board of Walks</h5>
                    </div>
                  </div>
                </div>
               </div>
        </div>
        {% endblock %}

app/templates/appointments.html
{% extends 'base.html' %}
{% block content %}
      <h1>Appointments</h1>
        <div class="jumbotron">
          <div class="row">
            <div class="col-6">
              <form method="post" actions="/appointments/">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit", name="save">add appointment</button>
              </form>
            </div>
          </div>
          <div class="row">
            {% for meh in appointments %}
              {% csrf_token %}
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{meh.getAppointmentName}}</h5>
                  <p class="card-text">{{meh.getDate}} {{meh.getTime}}</p>
                  <a class="btn btn-primary" href="/delete/{{meh.id}}">delete</a>
                </div>
              </div>
              {% endfor %}
            </div>
          <!--</div>-->
        </div>
{% endblock %}

app/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS: CHANGE IT LATER ON DJANGO STATIC -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.3.1/dist/css/bootstrap.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.css' %}"> -->

    <title>{% block title %}Tsaqif A{% endblock %}</title>
  </head>
  {% block body %}<body class= "container-noPads bg-myBlue"></body>{% endblock %}
      <nav class="navbar navbar-expand-lg navbar-light bg-myDark">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav ">
              <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white disabled" href="{% url 'app:aboutMe' %}" tabindex="-1" aria-disabled="true">About Me</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white disabled" href="{% url 'app:gallery' %}" tabindex="-1" aria-disabled="true">My Collections</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'app:appointments' %}">My Appointments</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white disabled" href="{% url 'app:contactMe' %}" tabindex="-1" aria-disabled="true">Contact Me</a>
              </li>
            </ul>
          </div>
        </nav>
        {% block content %}
        {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap-4.3.1/dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

app/templates/contactMe.html
{% extends 'base.html' %}
{% block title %}Contact Me{% endblock %}
      {% block content %}
        <div class="jumbotron">

        </div>
        {% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block body %}<body class= "container-noPads" style="width:100%; height:100%; background:#fff url('static/assets/newIndexBGimg.jpg') center center no-repeat;background-attachment: fixed;background-size:cover;">{% endblock %}
{% block content %}
        <h1 class="text-center text-white" style="position: relative;top: 250px;">Muhammad Tsaqif Al Bari</h1>
        <h2 class="text-center text-white" style="position: relative;top: 250px;">Designer. Coder. Googler Expert.</h2>
{% endblock %}

app/templates/mySchedule.html
{% extends 'base.html' %}
{% block title %}My Schedule{% endblock %}
    {% block content%}
    <div class="jumbotron justify-content-center">
            <table class="table" style="width: 50%">
                    <thead>
                        <tr>
                            <th scope="col">Mon</th>
                            <th scope="col">Tue</th>
                            <th scope="col">Wed</th>
                                <th scope="col">Thu</th>
                                <th scope="col">Fri</th>
                                <th scope="col">Sat</th>
                                <th scope="col">Sun</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{% if firstday.0 == 0 %}{% else %}{{firstday.0}}{% endif %}</th>
                                {% for i in w1 %}
                                <td>{% if i == 0 %}{% else %}{{i}}{% endif %}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <th scope="row">{% if firstday.1 == 0 %}{% else %}{{firstday.1}}{% endif %}</th>
                                {% for i in w2 %}
                                <td>{% if i == 0 %}{% else %}{{i}}{% endif %}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <th scope="row">{% if firstday.2 == 0 %}{% else %}{{firstday.2}}{% endif %}</th>
                                {% for i in w3 %}
                                <td>{% if i == 0 %}{% else %}{{i}}{% endif %}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <th scope="row">{% if firstday.3 == 0 %}{% else %}{{firstday.3}}{% endif %}</th>
                                {% for i in w4 %}
                                <td>{% if i == 0 %}{% else %}{{i}}{% endif %}</td>
                                {% endfor %}
                            </tr>
                            <tr>
                                <th scope="row">{% if firstday.4 == 0 %}{% else %}{{firstday.4}}{% endif %}</th>
                                {% for i in w5 %}
                                <td>{% if i == 0 %}{% else %}{{i}}{% endif %}</td>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
            <form method="post" actions="/schedule/" style="width: 50%">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit", name="save">add appointment</button>
            </form>
    </div>
    {% endblock %}